#spring.application.name=chat.app.backend
#server.port=8081
#spring.data.mongodb.uri=mongodb://localhost:27017/chatapp
spring.application.name=chat.app.backend
server.port=8081
spring.data.mongodb.uri=mongodb+srv://manukumar850a_db_user:TAY1ObhY3fChcMn2@cluster0.sypkazr.mongodb.net/chatapp?retryWrites=true&w=majority&appName=Cluster0
